name: First Workflow

on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World"
          echo "Another line"

      - name: Print a second step
        run: echo "Another Step"

      - name: print anothoer python line
        shell: python
        run: print("woow")
