name: First Workflow

on: [push, workflow_dispatch]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Info
        run: |
          hostname
          pwd
          ls -l /

      - name: Create a file
        run: |
          ls -al
          echo "One line" | tee myFile.log
          ls -al

      - name: A final step
        run: ls -al

  second-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "this is the end"
    steps:
      - name: Test environment variable
        run: |
          echo "value: ${{MY_ENV_VAR}}"
          echo "secret: ${{ secrets.MY_SECRET_VAR}}"
      - name:  get github context
        run: |
            echo " ${{ toJson(github)}}"
